### ISSUE TITLE
some questions to run the simulation plz help me!

### ISSUE THREAD

**Issue by imhere111** [KumarRobotics/semantics_manager#1]
I have already downloaded and compiled the Docker environment and code. What is the next step to run the ROS simulation? If the launch files under semantics_manager are for starting the drone and vehicle, where can I find the corresponding RViz map simulation files? Please help me with this. Thank you!

**Comment by iandouglas96** [comment]
Answered here: https://github.com/KumarRobotics/spomp-system/issues/5
